#ifndef ENUMS_H_INCLUDED
#define ENUMS_H_INCLUDED

enum Direction {
    DIR_BAS,
    DIR_BAS_GAUCHE,
    DIR_GAUCHE,
    DIR_HAUT_GAUCHE,
    DIR_HAUT,
    DIR_HAUT_DROITE,
    DIR_DROITE,
    DIR_BAS_DROITE,
    DIR_IMMOBILE
};

#endif // ENUMS_H_INCLUDED
